/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import shapes.AbstractShapeClass;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author Omar
 */
public class SuperFrame extends javax.swing.JFrame {
    
    protected SuperFrame caller;
    
    /**
     * Creates new form SuperFrame
     */
    public SuperFrame(SuperFrame caller) {
        caller.setVisible(false);
        this.setVisible(true);
        this.caller = caller;
    }
    
    public SuperFrame(){};
    
    
    protected void setup(){
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        //this.setVisible(true);       
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                caller.setVisible(true);
                dispose();
            }
        });
    }
    
    protected void pop(String line){
        popup pop = new popup(this, line);
    }
    
    protected void chooseColor(AbstractShapeClass shape){
       shape.setFillColor(JColorChooser.showDialog(null,"fill color choser", Color.RED));
       shape.setColor(JColorChooser.showDialog(null,"color choser", Color.RED));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void clear() {
        Container myContainer;
        myContainer = this.getContentPane();
        Component components[] = myContainer.getComponents();
        for (int i=0; i<components.length; i++) {
          if(components[i] instanceof JTextField) {
            JTextField tempTf = (JTextField) components[i];
            tempTf.setText("");
          }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
